import { Edit3, Plus, Search, Trash2 } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { EmptyState } from '../components/EmptyState';
import { Modal } from '../components/Modal';
import { PageHeader } from '../components/PageHeader';
import { Pagination } from '../components/Pagination';
import { useToast } from '../components/Toast';
import { useAppStore } from '../store/AppStore';
import type { Customer } from '../types';
import { formatDate, formatMoney } from '../utils/format';

const initial={ism:'',telefon:'',manzil:''}; type FormState=typeof initial&{id?:string};
export function CustomersPage(){
 const{data,saveCustomer,deleteCustomer}=useAppStore();const{showToast}=useToast();const[query,setQuery]=useState('');const[form,setForm]=useState<FormState>(initial);const[open,setOpen]=useState(false);const[deleteId,setDeleteId]=useState<string|null>(null);const[page,setPage]=useState(1);const pageSize=8;
 const filtered=useMemo(()=>data.customers.filter(c=>`${c.ism} ${c.telefon} ${c.manzil}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.ism.localeCompare(b.ism)),[data.customers,query]);const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const rows=filtered.slice((page-1)*pageSize,page*pageSize);
 const submit=(e:FormEvent)=>{e.preventDefault();if(!form.ism.trim()||!form.telefon.trim())return showToast('Mijoz ismi va telefoni majburiy.','warning');const r=saveCustomer(form);if(!r.ok)return showToast(r.message,'error');showToast(form.id?'Mijoz yangilandi.':'Mijoz qo‘shildi.');setOpen(false);setForm(initial)};const edit=(c:Customer)=>{const{createdAt:_,...rest}=c;setForm(rest);setOpen(true)};const remove=()=>{if(!deleteId)return;const r=deleteCustomer(deleteId);showToast(r.ok?'Mijoz o‘chirildi.':r.message,r.ok?'success':'error');setDeleteId(null)};
 return <div><PageHeader title="Mijozlar" description="Mijozlar bazasi, aloqa ma’lumotlari va savdo ko‘rsatkichlari." actions={<button className="btn-primary" onClick={()=>{setForm(initial);setOpen(true)}}><Plus size={18}/> Mijoz qo‘shish</button>}/><div className="card mb-4 p-4"><label className="relative block max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input className="input pl-10" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Ism, telefon yoki manzil..."/></label></div><div className="card overflow-hidden"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead className="table-head"><tr><th className="px-4 py-3">Mijoz</th><th className="px-4 py-3">Telefon</th><th className="px-4 py-3">Manzil</th><th className="px-4 py-3">Xaridlar soni</th><th className="px-4 py-3">Jami xarid</th><th className="px-4 py-3">Qolgan qarz</th><th className="px-4 py-3">Qo‘shilgan sana</th><th className="px-4 py-3 text-right">Amallar</th></tr></thead><tbody className="divide-y">{rows.map(c=>{const sales=data.sales.filter(s=>s.customerId===c.id);const debt=data.debts.filter(d=>d.mijozId===c.id).reduce((s,d)=>s+d.qolganQarz,0);return <tr key={c.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/40"><td className="px-4 py-3 font-semibold">{c.ism}</td><td className="px-4 py-3">{c.telefon}</td><td className="px-4 py-3">{c.manzil||'—'}</td><td className="px-4 py-3">{sales.length}</td><td className="px-4 py-3 font-semibold">{formatMoney(sales.reduce((sum,s)=>sum+s.items.reduce((lineSum,item)=>lineSum+item.miqdor*item.sotuvNarxi,0),0))}</td><td className={`px-4 py-3 font-semibold ${debt?'text-red-600':'text-emerald-600'}`}>{formatMoney(debt)}</td><td className="px-4 py-3">{formatDate(c.createdAt)}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><button className="rounded-lg p-2 text-blue-600 hover:bg-blue-50" onClick={()=>edit(c)}><Edit3 size={17}/></button><button className="rounded-lg p-2 text-red-600 hover:bg-red-50" onClick={()=>setDeleteId(c.id)}><Trash2 size={17}/></button></div></td></tr>})}</tbody></table></div>{!rows.length&&<EmptyState/>}<Pagination page={page} pages={pages} onChange={setPage}/></div>
 <Modal open={open} title={form.id?'Mijozni tahrirlash':'Yangi mijoz'} onClose={()=>setOpen(false)}><form onSubmit={submit} className="space-y-4"><div><label className="label">Mijoz ismi *</label><input className="input" value={form.ism} onChange={e=>setForm({...form,ism:e.target.value})}/></div><div><label className="label">Telefon *</label><input className="input" value={form.telefon} onChange={e=>setForm({...form,telefon:e.target.value})} placeholder="+998 90 123 45 67"/></div><div><label className="label">Manzil</label><input className="input" value={form.manzil} onChange={e=>setForm({...form,manzil:e.target.value})}/></div><div className="flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Bekor qilish</button><button className="btn-primary">Saqlash</button></div></form></Modal><ConfirmDialog open={Boolean(deleteId)} message="Savdo yoki qarz tarixi mavjud mijoz o‘chirilmaydi." onClose={()=>setDeleteId(null)} onConfirm={remove}/></div>
}
