import { useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { DateRangeFilter } from '../components/DateRangeFilter';
import { PageHeader } from '../components/PageHeader';
import { useAppStore } from '../store/AppStore';
import type { DateRange, Sale } from '../types';
import { grossProfitForSales, netCashFlow, sumByRange } from '../utils/calculations';
import { daysAgo, getPresetRange, isInRange } from '../utils/date';
import { formatMoney } from '../utils/format';

const colors = ['#2563eb', '#10b981', '#f59e0b'];
const total = (sale: Sale) => sale.items.reduce((sum, item) => sum + item.miqdor * item.sotuvNarxi, 0);

export function ReportsPage() {
  const { data } = useAppStore(); const month = getPresetRange('month'); const [range, setRange] = useState<DateRange>({ preset: 'month', ...month });
  const sales = data.sales.filter((sale) => isInRange(sale.sana, range.start, range.end)); const saleTotal = sales.reduce((sum, sale) => sum + total(sale), 0); const income = sumByRange(data.incomes, range.start, range.end); const expense = sumByRange(data.expenses, range.start, range.end); const gross = grossProfitForSales(data.sales, data.perfumes, range.start, range.end);
  const daily = useMemo(() => Array.from({ length: 30 }, (_, i) => { const sana = daysAgo(29 - i); return { name: sana.slice(5), savdo: data.sales.filter((sale) => sale.sana === sana).reduce((sum, sale) => sum + total(sale), 0), kirim: data.incomes.filter((item) => item.sana === sana).reduce((sum, item) => sum + item.summa, 0), chiqim: data.expenses.filter((item) => item.sana === sana).reduce((sum, item) => sum + item.summa, 0) }; }), [data]);
  const categories = useMemo(() => ['Erkaklar', 'Ayollar', 'Unisex'].map((kategoriya) => ({ name: kategoriya, value: sales.reduce((sum, sale) => sum + sale.items.filter((item) => data.perfumes.find((perfume) => perfume.id === item.perfumeId)?.kategoriya === kategoriya).reduce((lineSum, item) => lineSum + item.miqdor * item.sotuvNarxi, 0), 0) })), [data.perfumes, sales]);
  const topBrands = useMemo(() => { const map = new Map<string, number>(); sales.forEach((sale) => sale.items.forEach((item) => { const perfume = data.perfumes.find((value) => value.id === item.perfumeId); if (perfume) map.set(perfume.firmaNomi, (map.get(perfume.firmaNomi) ?? 0) + item.miqdor * item.sotuvNarxi); })); return [...map.entries()].map(([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value).slice(0, 7); }, [sales, data.perfumes]);
  return <div><PageHeader title="Hisobotlar" description="Savdo, foyda, pul oqimi va mahsulot kategoriyalari tahlili." actions={<DateRangeFilter value={range} onChange={setRange} />} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Jami savdo', saleTotal, ''], ['Real kirim', income, 'text-emerald-600'], ['Chiqim', expense, 'text-red-600'], ['Sof pul oqimi', netCashFlow(income, expense), netCashFlow(income, expense) >= 0 ? 'text-emerald-600' : 'text-red-600'], ['Hisoblangan foyda', gross - expense, gross - expense >= 0 ? 'text-emerald-600' : 'text-red-600']].map(([title, value, color]) => <div key={String(title)} className="card p-5"><p className="text-sm text-slate-500">{title}</p><p className={`mt-2 text-xl font-bold ${color}`}>{formatMoney(Number(value))}</p></div>)}</div>
    <div className="mt-6 card p-5"><h2 className="font-bold">30 kunlik savdo va pul oqimi</h2><div className="mt-5 h-80"><ResponsiveContainer><LineChart data={daily}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis tickFormatter={(value) => `${Math.round(value / 1000000)} mln`} tickLine={false} axisLine={false} width={65} /><Tooltip formatter={(value) => formatMoney(Number(value))} /><Legend /><Line type="monotone" dataKey="savdo" name="Savdo" stroke="#2563eb" strokeWidth={2} dot={false} /><Line type="monotone" dataKey="kirim" name="Kirim" stroke="#10b981" strokeWidth={2} dot={false} /><Line type="monotone" dataKey="chiqim" name="Chiqim" stroke="#ef4444" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><div className="card p-5"><h2 className="font-bold">Kategoriya bo‘yicha savdo</h2><div className="h-72"><ResponsiveContainer><PieChart><Pie data={categories} dataKey="value" nameKey="name" innerRadius={65} outerRadius={100} paddingAngle={3}>{categories.map((_, index) => <Cell key={index} fill={colors[index]} />)}</Pie><Tooltip formatter={(value) => formatMoney(Number(value))} /><Legend /></PieChart></ResponsiveContainer></div></div><div className="card p-5"><h2 className="font-bold">Firma bo‘yicha TOP savdo</h2><div className="h-72"><ResponsiveContainer><BarChart data={topBrands} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" tickFormatter={(value) => `${Math.round(value / 1000000)} mln`} /><YAxis type="category" dataKey="name" width={110} /><Tooltip formatter={(value) => formatMoney(Number(value))} /><Bar dataKey="value" name="Savdo" fill="#2563eb" radius={[0, 6, 6, 0]} /></BarChart></ResponsiveContainer></div></div></div>
  </div>;
}
