import { useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { DateRangeFilter } from '../components/DateRangeFilter';
import { PageHeader } from '../components/PageHeader';
import { useAppStore } from '../store/AppStore';
import type { DateRange } from '../types';
import { grossProfitForSales, netCashFlow, sumByRange } from '../utils/calculations';
import { daysAgo, getPresetRange, isInRange } from '../utils/date';
import { formatMoney } from '../utils/format';

const colors=['#2563eb','#10b981','#f59e0b'];
export function ReportsPage(){
 const{data}=useAppStore();const month=getPresetRange('month');const[range,setRange]=useState<DateRange>({preset:'month',...month});
 const sales=data.sales.filter(s=>isInRange(s.sana,range.start,range.end));const saleTotal=sales.reduce((sum,s)=>sum+s.miqdor*s.sotuvNarxi,0);const income=sumByRange(data.incomes,range.start,range.end);const expense=sumByRange(data.expenses,range.start,range.end);const gross=grossProfitForSales(data.sales,data.perfumes,range.start,range.end);
 const daily=useMemo(()=>Array.from({length:30},(_,i)=>{const sana=daysAgo(29-i);return{name:sana.slice(5),savdo:data.sales.filter(s=>s.sana===sana).reduce((sum,s)=>sum+s.miqdor*s.sotuvNarxi,0),kirim:data.incomes.filter(x=>x.sana===sana).reduce((sum,x)=>sum+x.summa,0),chiqim:data.expenses.filter(x=>x.sana===sana).reduce((sum,x)=>sum+x.summa,0)}}),[data]);
 const categories=useMemo(()=>['Erkaklar','Ayollar','Unisex'].map(kategoriya=>({name:kategoriya,value:data.sales.filter(s=>data.perfumes.find(p=>p.id===s.perfumeId)?.kategoriya===kategoriya&&isInRange(s.sana,range.start,range.end)).reduce((sum,s)=>sum+s.miqdor*s.sotuvNarxi,0)})),[data,range]);
 const topBrands=useMemo(()=>{const map=new Map<string,number>();sales.forEach(s=>{const p=data.perfumes.find(x=>x.id===s.perfumeId);if(p)map.set(p.firmaNomi,(map.get(p.firmaNomi)??0)+s.miqdor*s.sotuvNarxi)});return[...map.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value).slice(0,7)},[sales,data.perfumes]);
 return <div><PageHeader title="Hisobotlar" description="Savdo, foyda, pul oqimi va mahsulot kategoriyalari tahlili." actions={<DateRangeFilter value={range} onChange={setRange}/>}/>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><div className="card p-5"><p className="text-sm text-slate-500">Jami savdo</p><p className="mt-2 text-xl font-bold">{formatMoney(saleTotal)}</p></div><div className="card p-5"><p className="text-sm text-slate-500">Real kirim</p><p className="mt-2 text-xl font-bold text-emerald-600">{formatMoney(income)}</p></div><div className="card p-5"><p className="text-sm text-slate-500">Chiqim</p><p className="mt-2 text-xl font-bold text-red-600">{formatMoney(expense)}</p></div><div className="card p-5"><p className="text-sm text-slate-500">Sof pul oqimi</p><p className={`mt-2 text-xl font-bold ${netCashFlow(income,expense)>=0?'text-emerald-600':'text-red-600'}`}>{formatMoney(netCashFlow(income,expense))}</p></div><div className="card p-5"><p className="text-sm text-slate-500">Hisoblangan foyda</p><p className={`mt-2 text-xl font-bold ${gross-expense>=0?'text-emerald-600':'text-red-600'}`}>{formatMoney(gross-expense)}</p></div></div>
 <div className="mt-6 card p-5"><h2 className="font-bold">30 kunlik savdo va pul oqimi</h2><p className="text-sm text-slate-500">Kunlik savdo, real kirim va chiqim dinamikasi</p><div className="mt-5 h-80"><ResponsiveContainer><LineChart data={daily}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tickLine={false} axisLine={false}/><YAxis tickFormatter={v=>`${Math.round(v/1000000)} mln`} tickLine={false} axisLine={false} width={65}/><Tooltip formatter={v=>formatMoney(Number(v))}/><Legend/><Line type="monotone" dataKey="savdo" name="Savdo" stroke="#2563eb" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="kirim" name="Kirim" stroke="#10b981" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="chiqim" name="Chiqim" stroke="#ef4444" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></div>
 <div className="mt-6 grid gap-6 xl:grid-cols-2"><div className="card p-5"><h2 className="font-bold">Kategoriya bo‘yicha savdo</h2><p className="text-sm text-slate-500">Erkaklar, ayollar va unisex ulushi</p><div className="h-72"><ResponsiveContainer><PieChart><Pie data={categories} dataKey="value" nameKey="name" innerRadius={65} outerRadius={100} paddingAngle={3}>{categories.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip formatter={v=>formatMoney(Number(v))}/><Legend/></PieChart></ResponsiveContainer></div></div><div className="card p-5"><h2 className="font-bold">Firma bo‘yicha TOP savdo</h2><p className="text-sm text-slate-500">Tanlangan davrdagi eng katta savdo summasi</p><div className="h-72"><ResponsiveContainer><BarChart data={topBrands} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tickFormatter={v=>`${Math.round(v/1000000)} mln`} tickLine={false} axisLine={false}/><YAxis type="category" dataKey="name" width={110} tickLine={false} axisLine={false}/><Tooltip formatter={v=>formatMoney(Number(v))}/><Bar dataKey="value" name="Savdo" fill="#2563eb" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></div></div>
 </div>
}
