import { Moon, RefreshCcw, Save, Sun } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { PageHeader } from '../components/PageHeader';
import { useToast } from '../components/Toast';
import { useAppStore } from '../store/AppStore';
import type { AppSettings } from '../types';

export function SettingsPage(){
 const{data,updateSettings,resetDemo}=useAppStore();const{showToast}=useToast();const[form,setForm]=useState<AppSettings>(data.settings);const[confirm,setConfirm]=useState(false);useEffect(()=>setForm(data.settings),[data.settings]);
 const submit=(e:FormEvent)=>{e.preventDefault();if(!form.dokonNomi.trim())return showToast('Do‘kon nomini kiriting.','warning');updateSettings(form);showToast('Sozlamalar saqlandi.')};
 return <div><PageHeader title="Sozlamalar" description="Do‘kon ma’lumotlari, interfeys va demo bazani boshqarish."/><div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><form onSubmit={submit} className="card p-6"><h2 className="text-lg font-bold">Do‘kon ma’lumotlari</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className="label">Do‘kon nomi *</label><input className="input" value={form.dokonNomi} onChange={e=>setForm({...form,dokonNomi:e.target.value})}/></div><div><label className="label">Telefon</label><input className="input" value={form.telefon} onChange={e=>setForm({...form,telefon:e.target.value})}/></div><div><label className="label">Manzil</label><input className="input" value={form.manzil} onChange={e=>setForm({...form,manzil:e.target.value})}/></div><div><label className="label">Valyuta</label><select className="input" value={form.valyuta} onChange={e=>setForm({...form,valyuta:e.target.value})}><option>so‘m</option><option>USD</option></select></div></div><div className="mt-6 flex justify-end"><button className="btn-primary"><Save size={18}/> Sozlamalarni saqlash</button></div></form><div className="space-y-6"><div className="card p-6"><h2 className="text-lg font-bold">Interfeys ko‘rinishi</h2><p className="mt-1 text-sm text-slate-500">Yorug‘ yoki tungi rejimni tanlang.</p><button onClick={()=>{const next={...form,darkMode:!form.darkMode};setForm(next);updateSettings(next)}} className="mt-5 flex w-full items-center justify-between rounded-2xl border p-4 hover:bg-slate-50 dark:hover:bg-slate-800"><div className="flex items-center gap-3">{form.darkMode?<Moon className="text-blue-500"/>:<Sun className="text-amber-500"/>}<div className="text-left"><p className="font-semibold">{form.darkMode?'Tungi rejim':'Yorug‘ rejim'}</p><p className="text-xs text-slate-500">Darhol qo‘llanadi</p></div></div><span className={`relative h-7 w-12 rounded-full ${form.darkMode?'bg-blue-600':'bg-slate-300'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${form.darkMode?'left-6':'left-1'}`}/></span></button></div><div className="card border-red-200 p-6"><h2 className="text-lg font-bold text-red-600">Demo ma’lumotlar</h2><p className="mt-2 text-sm text-slate-500">Barcha o‘zgarishlarni o‘chirib, boshlang‘ich 20 ta parfyum va 30 kunlik demo ma’lumotlarni tiklaydi.</p><button className="btn-danger mt-5" onClick={()=>setConfirm(true)}><RefreshCcw size={18}/> Demo ma’lumotlarni tiklash</button></div></div></div><ConfirmDialog open={confirm} title="Demo bazani tiklash" message="Barcha LocalStorage ma’lumotlari o‘chadi va demo holatiga qaytadi. Bu amalni bekor qilib bo‘lmaydi." onClose={()=>setConfirm(false)} onConfirm={()=>{resetDemo();setConfirm(false);showToast('Demo ma’lumotlar qayta tiklandi.')}}/></div>
}
