import { Edit3, LockKeyhole, Plus, Search, Trash2 } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { useAppStore } from '../store/AppStore';
import type { ExpenseCategory, Income } from '../types';
import { today } from '../utils/date';
import { formatDate, formatMoney } from '../utils/format';
import { ConfirmDialog } from './ConfirmDialog';
import { EmptyState } from './EmptyState';
import { Modal } from './Modal';
import { PageHeader } from './PageHeader';
import { useToast } from './Toast';

const expenseCategories: ExpenseCategory[]=['Tovar xaridi','Ijara','Maosh','Transport','Reklama','Soliq','Boshqa'];
const incomeCategories: Income['kategoriya'][]=['Sotuv','Qarz to‘lovi','Boshqa'];

type FinanceForm={id?:string;kategoriya:string;summa:number;sana:string;izoh:string};
export function FinanceCrudPage({mode}:{mode:'income'|'expense'}){
 const{data,saveIncome,deleteIncome,saveExpense,deleteExpense}=useAppStore();const{showToast}=useToast();const items=mode==='income'?data.incomes:data.expenses;const categories=mode==='income'?incomeCategories:expenseCategories;const[query,setQuery]=useState('');const[category,setCategory]=useState('Barchasi');const[form,setForm]=useState<FinanceForm>({kategoriya:'Boshqa',summa:0,sana:today(),izoh:''});const[open,setOpen]=useState(false);const[deleteId,setDeleteId]=useState<string|null>(null);
 const rows=useMemo(()=>items.filter(item=>item.izoh.toLowerCase().includes(query.toLowerCase())&&(category==='Barchasi'||item.kategoriya===category)).sort((a,b)=>b.sana.localeCompare(a.sana)),[items,query,category]);
 const submit=(e:FormEvent)=>{e.preventDefault();if(form.summa<=0||!form.sana)return showToast('Summa va sanani to‘g‘ri kiriting.','warning');const result=mode==='income'?saveIncome({id:form.id,kategoriya:form.kategoriya as Income['kategoriya'],summa:form.summa,sana:form.sana,izoh:form.izoh}):saveExpense({id:form.id,kategoriya:form.kategoriya as ExpenseCategory,summa:form.summa,sana:form.sana,izoh:form.izoh});if(!result.ok)return showToast(result.message,'error');showToast(`${mode==='income'?'Kirim':'Chiqim'} saqlandi.`);setOpen(false)};
 const edit=(item:typeof items[number])=>{if(item.sourceId)return showToast('Avtomatik operatsiya manba sahifasidan boshqariladi.','warning');setForm({id:item.id,kategoriya:item.kategoriya,summa:item.summa,sana:item.sana,izoh:item.izoh});setOpen(true)};
 const remove=()=>{if(!deleteId)return;const result=mode==='income'?deleteIncome(deleteId):deleteExpense(deleteId);showToast(result.ok?`${mode==='income'?'Kirim':'Chiqim'} o‘chirildi.`:result.message,result.ok?'success':'error');setDeleteId(null)};
 const total=rows.reduce((s,i)=>s+i.summa,0);const isIncome=mode==='income';
 return <div><PageHeader title={isIncome?'Kirimlar':'Chiqimlar'} description={isIncome?'Real pul kirimlari: savdo, qarz to‘lovi va boshqa tushumlar.':'Do‘kon xarajatlari va ularning kategoriyalari.'} actions={<button className="btn-primary" onClick={()=>{setForm({kategoriya:'Boshqa',summa:0,sana:today(),izoh:''});setOpen(true)}}><Plus size={18}/> {isIncome?'Kirim':'Chiqim'} qo‘shish</button>}/>
 <div className="mb-4 grid gap-4 lg:grid-cols-[1fr_auto]"><div className="card grid gap-3 p-4 md:grid-cols-2"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input className="input pl-10" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Izoh bo‘yicha qidirish..."/></label><select className="input" value={category} onChange={e=>setCategory(e.target.value)}><option>Barchasi</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className={`card min-w-64 p-5 ${isIncome?'border-emerald-200':'border-red-200'}`}><p className="text-sm text-slate-500">Filtr bo‘yicha jami</p><p className={`mt-2 text-2xl font-bold ${isIncome?'text-emerald-600':'text-red-600'}`}>{formatMoney(total)}</p></div></div>
 <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="min-w-[850px] w-full text-sm"><thead className="table-head"><tr><th className="px-4 py-3">Sana</th><th className="px-4 py-3">Kategoriya</th><th className="px-4 py-3">Izoh</th><th className="px-4 py-3">Manba</th><th className="px-4 py-3">Summa</th><th className="px-4 py-3 text-right">Amallar</th></tr></thead><tbody className="divide-y">{rows.map(item=><tr key={item.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/40"><td className="px-4 py-3">{formatDate(item.sana)}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${isIncome?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700'}`}>{item.kategoriya}</span></td><td className="px-4 py-3">{item.izoh||'—'}</td><td className="px-4 py-3">{item.sourceId?<span className="inline-flex items-center gap-1 text-xs text-slate-500"><LockKeyhole size={14}/> Avtomatik</span>:<span className="text-xs text-blue-600">Qo‘lda</span>}</td><td className={`px-4 py-3 font-bold ${isIncome?'text-emerald-600':'text-red-600'}`}>{isIncome?'+':'-'} {formatMoney(item.summa)}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><button className="rounded-lg p-2 text-blue-600 hover:bg-blue-50 disabled:opacity-30" disabled={Boolean(item.sourceId)} onClick={()=>edit(item)}><Edit3 size={17}/></button><button className="rounded-lg p-2 text-red-600 hover:bg-red-50 disabled:opacity-30" disabled={Boolean(item.sourceId)} onClick={()=>setDeleteId(item.id)}><Trash2 size={17}/></button></div></td></tr>)}</tbody></table></div>{!rows.length&&<EmptyState/>}</div>
 <Modal open={open} title={`${form.id?'Tahrirlash':'Yangi'} ${isIncome?'kirim':'chiqim'}`} onClose={()=>setOpen(false)}><form onSubmit={submit} className="space-y-4"><div><label className="label">Kategoriya</label><select className="input" value={form.kategoriya} onChange={e=>setForm({...form,kategoriya:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div><label className="label">Summa *</label><input className="input" type="number" min="1" value={form.summa} onChange={e=>setForm({...form,summa:Number(e.target.value)})}/></div><div><label className="label">Sana</label><input className="input" type="date" value={form.sana} onChange={e=>setForm({...form,sana:e.target.value})}/></div><div><label className="label">Izoh</label><textarea className="input min-h-24" value={form.izoh} onChange={e=>setForm({...form,izoh:e.target.value})}/></div><div className="flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Bekor qilish</button><button className="btn-primary">Saqlash</button></div></form></Modal><ConfirmDialog open={Boolean(deleteId)} message={`${isIncome?'Kirim':'Chiqim'} yozuvini o‘chirishni tasdiqlaysizmi?`} onClose={()=>setDeleteId(null)} onConfirm={remove}/></div>
}
